// A fixed scripted playthrough shared by the smoke suite (Node) and the boot
// page (browser). Both environments must produce the identical fingerprint.
// The script exercises every verb (including the new ATTUNE effect-gating,
// the multi-offer quest chain, and the branching reveal order) and completes
// the whole chapter. Over-issued attacks past a kill are safe (`already_down`,
// never a throw), so combat loops carry generous margins and stay robust
// across any seed.
//
// Movement is generated by a path stepper over the region's KNOWN static
// coordinates, explicitly routing through the (16,12) ridge gap whenever a
// waypoint crosses from one side of the x=16 wall column to the other.

export const DEMO_SEED = 0x5c1e5; // "skies"

const sign = (n) => (n > 0 ? 1 : n < 0 ? -1 : 0);

export function demoCommands() {
  const cmds = [];
  const cur = { x: 3, y: 12 }; // spawn
  const M = (dx, dy) => cmds.push({ type: 'MOVE', dx, dy });
  const walkToRaw = (tx, ty) => {
    while (cur.x !== tx || cur.y !== ty) {
      const dx = sign(tx - cur.x), dy = sign(ty - cur.y);
      M(dx, dy);
      cur.x += dx; cur.y += dy;
    }
  };
  // Always route via an L-path through the y=12 gap: vertical at the current
  // x, horizontal along the open y=12 row, vertical at the target x. Safe
  // unconditionally (no "which side" detection needed) as long as no
  // waypoint sits exactly on x=16, which none of ours do — a straight
  // diagonal walk can otherwise land ON a blocked ridge tile before reaching
  // the gap (e.g. crossing from (22,5) toward (16,12) diagonally reaches
  // (16,11), which IS blocked, one step early).
  const walkTo = (tx, ty) => {
    walkToRaw(cur.x, 12);
    walkToRaw(tx, 12);
    walkToRaw(tx, ty);
  };
  const charge = (n) => { cmds.push({ type: 'CHARGE', start: true }); for (let i = 1; i < n; i++) cmds.push({ type: 'CHARGE' }); };

  cmds.push({ type: 'TICK' });

  // --- Quest 1: Hear the World (resonance well / audio) ---------------------
  walkTo(4, 12);
  cmds.push({ type: 'TALK', npcId: 'sable' }); // offers only 'hear-the-world'
  cmds.push({ type: 'ACCEPT_QUEST', questId: 'hear-the-world' });
  // Try the WRONG well first — a vague non-effect hint, never a throw —
  // proving effect-gating (not existence-gating) works before the real one.
  walkTo(12, 8);
  cmds.push({ type: 'ATTUNE', wellId: 'playerwell' }); // well_hint, no effect
  // Resonance sits at the far corner of the Reach — the real trek.
  walkTo(39, 23);
  cmds.push({ type: 'ATTUNE', wellId: 'resonance' }); // real effect: audio on

  // Some free-roam combat + a destructible, exercised while wandering.
  walkTo(6, 9);
  cmds.push({ type: 'BREAK', destructibleId: 'crate1' });
  walkTo(10, 5);
  for (let i = 0; i < 4; i++) cmds.push({ type: 'MELEE', enemyId: 'wisp1' });

  // --- Quests 2-4: the branching sprite-reveal chain -------------------------
  // First pick: player. Talking now offers all 3 reveal-* quests at once.
  walkTo(4, 12);
  cmds.push({ type: 'TALK', npcId: 'sable' }); // offers reveal-player/world/enemies
  cmds.push({ type: 'ACCEPT_QUEST', questId: 'reveal-player' });
  walkTo(12, 8);
  cmds.push({ type: 'ATTUNE', wellId: 'playerwell' }); // real effect now: visual.player

  // Second pick: world. Re-talking offers the 2 remaining.
  walkTo(4, 12);
  cmds.push({ type: 'TALK', npcId: 'sable' }); // offers reveal-world/enemies
  cmds.push({ type: 'ACCEPT_QUEST', questId: 'reveal-world' });
  walkTo(20, 16);
  cmds.push({ type: 'ATTUNE', wellId: 'worldwell' });

  // Third (forced) pick: enemies — the one thread left.
  walkTo(4, 12);
  cmds.push({ type: 'TALK', npcId: 'sable' }); // offers reveal-enemies only
  cmds.push({ type: 'ACCEPT_QUEST', questId: 'reveal-enemies' });
  walkTo(22, 5);
  cmds.push({ type: 'ATTUNE', wellId: 'enemywell' });

  // --- Quest 5: Mend the Sky (finale) ----------------------------------------
  walkTo(4, 12);
  cmds.push({ type: 'TALK', npcId: 'sable' }); // offers mend-the-sky-finale
  cmds.push({ type: 'ACCEPT_QUEST', questId: 'mend-the-sky-finale' });

  // Gloomhide (immune: aura). Wrong method first — a blast bounces off —
  // then finish it with fists.
  walkTo(13, 12);
  charge(5);
  cmds.push({ type: 'AURA_BLAST', enemyId: 'gloom1' }); // no_effect
  for (let i = 0; i < 5; i++) cmds.push({ type: 'MELEE', enemyId: 'gloom1' });

  // Shardling (immune: melee). Wrong method first, then shatter with aura.
  walkTo(22, 11);
  cmds.push({ type: 'MELEE', enemyId: 'shard1' }); // no_effect
  charge(6);
  cmds.push({ type: 'AURA_BLAST', enemyId: 'shard1' });
  cmds.push({ type: 'AURA_BLAST', enemyId: 'shard1' });
  charge(6);
  cmds.push({ type: 'AURA_BLAST', enemyId: 'shard1' });
  cmds.push({ type: 'AURA_BLAST', enemyId: 'shard1' });

  // Collect the lens shard.
  walkTo(26, 18);
  cmds.push({ type: 'INTERACT', pickupId: 'lens1' });

  // Attune the light well — the finale reveal (occlusion/shadows + the
  // presentation-only kaleidoscope hue-cycle for whatever sprites are on).
  walkTo(28, 6);
  cmds.push({ type: 'ATTUNE', wellId: 'lightwell' });

  // A Hollow Echo guards the road east.
  walkTo(30, 19);
  cmds.push({ type: 'ENEMY_STRIKE', enemyId: 'echo1' });
  cmds.push({ type: 'BUY', itemId: 'emberdraught' });
  cmds.push({ type: 'USE_ITEM', itemId: 'emberdraught' });
  charge(6);
  cmds.push({ type: 'AURA_BLAST', enemyId: 'echo1' });
  cmds.push({ type: 'AURA_BLAST', enemyId: 'echo1' });
  for (let i = 0; i < 4; i++) cmds.push({ type: 'MELEE', enemyId: 'echo1' });

  // Reach the rift's edge — the last objective. The sky is mended; the
  // Second rises.
  walkTo(35, 12);

  // Face the Second.
  walkTo(36, 12);
  for (let cyc = 0; cyc < 6; cyc++) {
    charge(6);
    cmds.push({ type: 'AURA_BLAST', enemyId: 'rival1' });
    cmds.push({ type: 'AURA_BLAST', enemyId: 'rival1' });
    cmds.push({ type: 'MELEE', enemyId: 'rival1' });
    cmds.push({ type: 'MELEE', enemyId: 'rival1' });
    if (cyc === 1) cmds.push({ type: 'ENEMY_STRIKE', enemyId: 'rival1' });
  }

  cmds.push({ type: 'CHOOSE_FATE', fate: 'claim' });
  walkTo(39, 12);
  cmds.push({ type: 'TICK' });
  cmds.push({ type: 'TICK' });

  return cmds;
}
