// A fixed scripted playthrough shared by the smoke suite (Node) and the boot
// page (browser). Both environments must produce the identical fingerprint.
// The script exercises EVERY sim verb at least once and completes the whole
// chapter (mend the sky, face the Second, choose, step through the rift).
// Over-issued attacks past a kill are safe (a downed enemy answers with an
// `already_down` event, never a throw), so the combat loops carry generous
// margins and stay robust across ANY seed — this also runs against the title
// screen's own boot seed, not just DEMO_SEED.
//
// Movement is generated by a path stepper over the region's KNOWN static
// coordinates. Waypoints are chosen so no diagonal ever crosses the blocked
// ridge at x=16 (the only crossing is the open gap at y=12, taken by pure-east
// steps), keeping the stepper's cursor perfectly in sync with the sim.

export const DEMO_SEED = 0x5c1e5; // "skies"

const sign = (n) => (n > 0 ? 1 : n < 0 ? -1 : 0);

export function demoCommands() {
  const cmds = [];
  const cur = { x: 3, y: 12 }; // spawn
  const M = (dx, dy) => cmds.push({ type: 'MOVE', dx, dy });
  // Step to (tx,ty) along a clear diagonal-then-straight path; keeps `cur` in
  // lockstep with the sim (every move here lands on a non-blocked tile).
  const walkTo = (tx, ty) => {
    while (cur.x !== tx || cur.y !== ty) {
      const dx = sign(tx - cur.x), dy = sign(ty - cur.y);
      M(dx, dy);
      cur.x += dx; cur.y += dy;
    }
  };
  const charge = (n) => { cmds.push({ type: 'CHARGE', start: true }); for (let i = 1; i < n; i++) cmds.push({ type: 'CHARGE' }); };

  cmds.push({ type: 'TICK' });

  // Meet Sable, take the offer, accept it (spawns the gated enemies/pickup/wells).
  walkTo(4, 12);
  cmds.push({ type: 'TALK', npcId: 'sable' });
  cmds.push({ type: 'ACCEPT_QUEST', questId: 'mend-the-sky' });

  // Attune the resonance well — sound returns (a standalone, always-present well).
  walkTo(7, 12);
  cmds.push({ type: 'ATTUNE', wellId: 'resonance' });

  // Break the supply crate for coins.
  walkTo(6, 10);
  cmds.push({ type: 'BREAK', destructibleId: 'crate1' });

  // Cull a free-roam Palewisp on the way north (not immune — fists land).
  walkTo(10, 6);
  for (let i = 0; i < 4; i++) cmds.push({ type: 'MELEE', enemyId: 'wisp1' });

  // Attune the colour well — the grey lifts (objective: attune color).
  walkTo(12, 8);
  cmds.push({ type: 'ATTUNE', wellId: 'colorwell' });

  // Prove collision: bump the blocked ridge (16,10) — a `blocked` refusal, no move.
  walkTo(15, 10);
  M(1, 0); // into (16,10): blocked, cursor stays put

  // Gloomhide (immune: aura). Try the WRONG method first — a blast bounces off
  // (`no_effect`, never a silent no-op) — then finish it with fists.
  walkTo(13, 12);
  charge(5);
  cmds.push({ type: 'AURA_BLAST', enemyId: 'gloom1' }); // no_effect
  for (let i = 0; i < 5; i++) cmds.push({ type: 'MELEE', enemyId: 'gloom1' });

  // Cross the ridge at the y=12 gap, then attune the light well.
  walkTo(17, 12);
  walkTo(20, 16);
  cmds.push({ type: 'ATTUNE', wellId: 'lightwell' });

  // Shardling (immune: melee). Wrong method first again — a punch does nothing
  // — then shatter it with aura.
  walkTo(22, 11);
  cmds.push({ type: 'MELEE', enemyId: 'shard1' }); // no_effect
  charge(6);
  cmds.push({ type: 'AURA_BLAST', enemyId: 'shard1' });
  cmds.push({ type: 'AURA_BLAST', enemyId: 'shard1' });
  charge(6);
  cmds.push({ type: 'AURA_BLAST', enemyId: 'shard1' });
  cmds.push({ type: 'AURA_BLAST', enemyId: 'shard1' });

  // Collect the lens shard (objective: collect).
  walkTo(26, 18);
  cmds.push({ type: 'INTERACT', pickupId: 'lens1' });

  // Attune the depth well — the world stands up (objective: attune depth).
  walkTo(28, 6);
  cmds.push({ type: 'ATTUNE', wellId: 'depthwell' });

  // A Hollow Echo guards the road east. Take a hit from it (player_hit), buy
  // and drink a draught (BUY/USE_ITEM), then put it down.
  walkTo(30, 19);
  cmds.push({ type: 'ENEMY_STRIKE', enemyId: 'echo1' });
  cmds.push({ type: 'BUY', itemId: 'emberdraught' });
  cmds.push({ type: 'USE_ITEM', itemId: 'emberdraught' });
  charge(6);
  cmds.push({ type: 'AURA_BLAST', enemyId: 'echo1' });
  cmds.push({ type: 'AURA_BLAST', enemyId: 'echo1' });
  for (let i = 0; i < 4; i++) cmds.push({ type: 'MELEE', enemyId: 'echo1' });

  // Reach the rift's edge — the last objective. The sky is mended; the Second
  // rises (boss_appeared).
  walkTo(35, 12);

  // Face the Second (hp 40; taunts and hardens at half health). Generous cycles
  // guarantee the kill at minimum damage rolls, over-attacks are safe.
  walkTo(36, 12);
  for (let cyc = 0; cyc < 6; cyc++) {
    charge(6);
    cmds.push({ type: 'AURA_BLAST', enemyId: 'rival1' });
    cmds.push({ type: 'AURA_BLAST', enemyId: 'rival1' });
    cmds.push({ type: 'MELEE', enemyId: 'rival1' });
    cmds.push({ type: 'MELEE', enemyId: 'rival1' });
    if (cyc === 1) cmds.push({ type: 'ENEMY_STRIKE', enemyId: 'rival1' }); // take one blow
  }

  // Claim its power (the choice that travels into saga.v2), then step through
  // the open rift — the chapter ends.
  cmds.push({ type: 'CHOOSE_FATE', fate: 'claim' });
  walkTo(39, 12);
  cmds.push({ type: 'TICK' });
  cmds.push({ type: 'TICK' });

  return cmds;
}
